version: '3.8'

services:
  queue-writer-redis-rdb:
    image: queue-client-compare
    container_name: queue-writer-redis-rdb
    build:
      context: .
    environment:
      - REDIS_HOST=redis-queue-rdb
      - REDIS_PORT=6379
      - QUEUE_ITEMS_COUNT=50000
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/set_to_redis.php" ]
    depends_on:
      - redis_rdb

  queue-reader-redis-rdb:
    image: queue-client-compare
    container_name: queue-reader-redis-rdb
    build:
      context: .
    environment:
      - REDIS_HOST=redis-queue-rdb
      - REDIS_PORT=6379
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/read_from_redis.php" ]
    depends_on:
      - redis_rdb

  queue-writer-redis-aof:
    image: queue-client-compare
    container_name: queue-writer-redis-aof
    build:
      context: .
    environment:
      - REDIS_HOST=redis-queue-aof
      - REDIS_PORT=6379
      - QUEUE_ITEMS_COUNT=50000
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/set_to_redis.php" ]
    depends_on:
      - redis_aof

  queue-reader-redis-aof:
    image: queue-client-compare
    container_name: queue-reader-redis-aof
    build:
      context: .
    environment:
      - REDIS_HOST=redis-queue-aof
      - REDIS_PORT=6379
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/read_from_redis.php" ]
    depends_on:
      - redis_aof

  beanstalkd-writer:
    image: queue-client-compare
    container_name: beanstalkd-writer
    build:
      context: .
    environment:
      - QUEUE_HOST=beanstalkd
      - QUEUE_PORT=11300
      - QUEUE_ITEMS_COUNT=50000
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/set_to_beanstalkd.php" ]
    depends_on:
      - beanstalkd

  beanstalkd-reader:
    image: queue-client-compare
    container_name: beanstalkd-reader
    build:
      context: .
    environment:
      - QUEUE_HOST=beanstalkd
      - QUEUE_PORT=11300
    volumes:
      - "./:/usr/src/app"
    networks:
      - queue-compare
    command: [ "php", "./src/read_from_beanstalkd.php" ]
    depends_on:
      - beanstalkd

  redis_rdb:
    image: redis:6.2.6
    container_name: redis-queue-rdb
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - "./conf/redis/master_rdb.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - queue-compare
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis_aof:
    image: redis:6.2.6
    container_name: redis-queue-aof
    restart: unless-stopped
    ports:
      - "18379:6379"
    volumes:
      - "./conf/redis/master_aof.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - queue-compare
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    restart: unless-stopped
    ports:
      - "11300:11300"
    networks:
      - queue-compare

networks:
  queue-compare:
    driver: bridge